/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snakegame;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.Timer;

/**
 *
 * @author Lokesh Chandra
 */
public class MultiPlay extends javax.swing.JFrame {

    /**
     * Creates new form MultiPlay
     */
    Timer ti,tii,tiii;
    TimerTask tti,ttii,tttiii;
    public MultiPlay() {
        initComponents();
        MakeOnline mk = new MakeOnline();
        retrieveOnlineUsers();
        retrieveReqUsers();
        setLocationRelativeTo(null);
    }

    public void retrieveReqUsers()
    {
        
        
        
        
        try
        {
            MySql msql = new MySql();
            String sql = "select requser from req where userid = '"+Login.uid+"'";
            PreparedStatement pstmt = msql.conn.prepareStatement(sql);
            
            tiii = new Timer();
            tiii.schedule(tttiii = new TimerTask()
            { 
            public void run()
            {
            
                try {
                    String usid = null;
                    DefaultListModel model = new DefaultListModel();
                    int count = 0 ;
                    ResultSet rs = pstmt.executeQuery();
                    
                    while(rs.next())
                    {
                        usid  = rs.getString(1);
                        model.add(count++,usid);
                        
                    }   
                    requesteduser.setModel(model);
                } catch (SQLException ex) {
                    Logger.getLogger(MultiPlay.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            },0, 1000);
        }
        catch(SQLException e)
        {e.printStackTrace();}
    }
    
    public void retrieveOnlineUsers()
    {
        
       
        
        
        try
        {
            MySql msql = new MySql();
            String sql = "select userid from info where status = '1' and userid != '"+Login.uid+"'";
            PreparedStatement pstmt = msql.conn.prepareStatement(sql);
            
            tii = new Timer();
            tii.schedule(ttii = new TimerTask()
            { 
            public void run()
            {
                try {
                     DefaultListModel model = new DefaultListModel();
                        int count = 0 ;
                        String usid = null;
                        ResultSet rs = pstmt.executeQuery();

                        while(rs.next())
                        {

                            usid  = rs.getString(1);
                            model.add(count++,usid);
                            
                        }   
                        onlineuser.setModel(model);
                } catch (SQLException ex) {
                    Logger.getLogger(MultiPlay.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            },0, 1000);
        }
        catch(SQLException e)
        {e.printStackTrace();}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        multi_back = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        onlineuser = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        requesteduser = new javax.swing.JList<>();
        waitingbox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Requested Gamers");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 170, 30));

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 0));
        jLabel2.setText("Online Gamers");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 30));

        multi_back.setBackground(new java.awt.Color(0, 0, 0));
        multi_back.setForeground(new java.awt.Color(255, 255, 255));
        multi_back.setText("Back");
        multi_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multi_backActionPerformed(evt);
            }
        });
        jPanel1.add(multi_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 90, -1));

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setForeground(new java.awt.Color(51, 204, 0));

        onlineuser.setBackground(new java.awt.Color(0, 0, 0));
        onlineuser.setFont(new java.awt.Font("HP Simplified Light", 1, 20)); // NOI18N
        onlineuser.setForeground(new java.awt.Color(51, 204, 0));
        onlineuser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        onlineuser.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                onlineuserValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(onlineuser);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 270, 360));

        jScrollPane3.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setForeground(new java.awt.Color(51, 204, 0));

        requesteduser.setBackground(new java.awt.Color(0, 0, 0));
        requesteduser.setFont(new java.awt.Font("HP Simplified Light", 1, 20)); // NOI18N
        requesteduser.setForeground(new java.awt.Color(255, 102, 51));
        requesteduser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        requesteduser.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                requesteduserValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(requesteduser);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 270, 360));

        waitingbox.setEditable(false);
        waitingbox.setBackground(new java.awt.Color(0, 0, 0));
        waitingbox.setFont(new java.awt.Font("HP Simplified Light", 0, 30)); // NOI18N
        waitingbox.setForeground(new java.awt.Color(255, 255, 51));
        waitingbox.setBorder(null);
        jPanel1.add(waitingbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 270, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multi_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multi_backActionPerformed
        // TODO add your handling code here:
        
        Welcome wl = new Welcome();
        wl.namebox.setText(Login.nm);
        wl.highscorebox.setText(Login.sc);
        wl.setVisible(true);
        dispose();
    }//GEN-LAST:event_multi_backActionPerformed

    static String s = null;
    private void onlineuserValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_onlineuserValueChanged
        if(evt.getValueIsAdjusting())
                return;
        
        s = onlineuser.getSelectedValue().toString();
        
        
        try {
            // TODO add your handling code here:

            MySql msql = new MySql();
            String sql = "insert into req (userid, requser) values ('"+s+"','"+Login.uid+"')";
            PreparedStatement pstmt = msql.conn.prepareStatement(sql);
            
            int i = pstmt.executeUpdate();
            if(i>0)
                JOptionPane.showMessageDialog(null, "Reuqest sent successfully to "+s+" Please Wait .......");
            else
                JOptionPane.showMessageDialog(null, "Request Not sent...!!!!");
        } catch (SQLException ex) {
            Logger.getLogger(MultiPlay.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
        try{
        String sql = "select status from req where userid = '"+s+"' and requser = '"+Login.uid+"'";
        MySql msql = new MySql();
        PreparedStatement pstmt = msql.conn.prepareStatement(sql);
        
        ti = new Timer();
        ti.schedule(tti = new TimerTask()
        { 
            public void run()
            {
                try {
                    String st=null;
                    ResultSet rs = pstmt.executeQuery();
                    while(rs.next()){
                        st = rs.getString(1);
                    }
                    if("1".equals(st)){
                       
                        SnakeGame sg = new SnakeGame();
                        sg.playstatusbox.setText("Multi Play");
                        sg.player2box.setText(s);
                        sg.player1box.setText(Login.uid);
                        System.out.println(s);
                        sg.setVisible(true);
                        dispose();
                        ti.cancel();
                    }
                    else{
                        waitingbox.setText("Waiting ...");
                        System.out.println("Value : "+s);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(MultiPlay.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
          
        },0, 1000);
        }
        catch(SQLException ex){
        ex.printStackTrace();}
    }//GEN-LAST:event_onlineuserValueChanged

    private void requesteduserValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_requesteduserValueChanged
        try {
            // TODO add your handling code here:
            if(evt.getValueIsAdjusting())
                return;
            
            String r = requesteduser.getSelectedValue().toString();
            String sql = "update req set status = '1' where userid ='"+Login.uid+"' and requser = '"+r+"'";
            MySql msql = new MySql();
            PreparedStatement pstmt = msql.conn.prepareStatement(sql);
            int i = pstmt.executeUpdate();
            
            if(i>0){
                System.out.println("Play Game ..reuqest accepted");
                s = r;
                SnakeGame sg = new SnakeGame();
                sg.playstatusbox.setText("Multi Play");
                sg.player1box.setText(Login.uid);
                sg.player2box.setText(r);
                
                System.out.println("Req : "+s);
                sg.setVisible(true);
                dispose();
            }
            else
                System.out.println("Error in request acceptance ....!!!!");
        } catch (SQLException ex) {
            Logger.getLogger(MultiPlay.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_requesteduserValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiPlay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiPlay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton multi_back;
    private javax.swing.JList<String> onlineuser;
    private javax.swing.JList<String> requesteduser;
    private javax.swing.JTextField waitingbox;
    // End of variables declaration//GEN-END:variables
}
